language: python
python:
  - "2.7"
  - "3.5"
script: nosetests
notifications:
  email: false

install:
  - if [[ $TRAVIS_PYTHON_VERSION > 3 ]]; then pip install -r requirements3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION < 3 ]]; then pip install -r requirements2.txt; fi
