language: python
dist: xenial
sudo: required
addons:
  apt:
    packages:
      - python3-pip

before_install:
  sudo python3 -m pip install nose2

python:
  - "2.7"
  - "3.5"
script: nose2
notifications:
  email: false

install:
  pip install -r requirements.txt
